name: systori
version: 0.0.1
description: >
  Systori components written in Dart.
dependencies:
  intl: any
  web_components: any
  parsers: any
  quiver: any
    #git:
    #  url: git://github.com/google/quiver-dart.git
    #  ref: master
    #path: ../../../quiver-dart
dev_dependencies:
  test:
    git:
      url: git://github.com/dart-lang/test.git
      ref: master
    #path: ../../../test
transformers:
  - $dart2js:
      $include:
        - web/adjustment_editor.dart
        - web/field.dart
        - web/field_planning.dart
        - web/invoice_editor.dart
        - web/job_editor.dart
        - web/payment_editor.dart
        - web/project_list.dart
        - web/proposal_editor.dart
        - web/refund_editor.dart
        - web/timetracking.dart
        - web/goto_project.dart
        - web/notes.dart
        - web/notes_dashboard.dart
      commandLineOptions: [--show-package-warnings]
