# Generated by Django 2.1.8 on 2019-07-30 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontact',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='project.Project'),
        ),
        migrations.AddField(
            model_name='contact',
            name='projects',
            field=models.ManyToManyField(related_name='contacts', through='directory.ProjectContact', to='project.Project'),
        ),
    ]
