name: systori

layers:
  base:
    from: damoti/base:latest
    apt-get:
      - language-pack-de
      - libpq-dev
      - postgresql-client
      - libjpeg-dev
      - libxml2-dev
      - libxslt-dev
      - libffi-dev
    context:
      - requirements/base.pip
    build:
      - pip3 install -r requirements/base.pip
  app:
    context:
      - .
    build:
      - cd systori/dart && pub get && pub build && cd -
      - pip3 install --src=/src -r requirements/app.pip
      - export DJANGO_SETTINGS_MODULE=systori.settings.common
      - python3 manage.py collectstatic --noinput
    prepare: fab prepare:service={service},branch={git-branch}
    start: fab uwsgi
    wait-for: db:5432
  test:
    build:
      - pip3 install -r requirements/test.pip
    start: fab test
    wait-for: db:5432

ssh:
  known_hosts:
    - github.com
    - bitbucket.org

slack:
  events:
    - build.failure
    - test.success
    - test.failure
    - deployment.success
    - deployment.failure
  api: https://hooks.slack.com/services/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

build:
  branches:
    - dev
