# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields

def edit_fields(apps, schema_editor):
    Invoice = apps.get_model("document", "Invoice")
    for invoice in Invoice.objects.all():
        if invoice.json.get('total')

class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20160906_1650.py'),
    ]

    operations = [
        migrations.RunPython(edit_fields),
    ]
