FROM google/dart:1.24.3

COPY systori/dart/sdk/html_dart2js.dart /usr/lib/dart/lib/html/dart2js/html_dart2js.dart
COPY /dart-sdk/lib/html/dart2js/html_dart2js.dart /dart-sdk/lib/html/dart2js/bkp_html_dart2js.dart
COPY systori/dart/sdk/html_dart2js.dart /dart-sdk/lib/html/dart2js/html_dart2js.dart
