# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 02:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160403_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access', to=settings.AUTH_USER_MODEL),
        ),
    ]
