# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-31 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from postgres_schema.operations import RunInSchemas


def create_worker_flags(apps, schema_editor):
    Worker = apps.get_model("company", "Worker")
    WorkerFlags = apps.get_model("company", "WorkerFlags")
    for worker in Worker.objects.filter(flags__isnull=True):
        WorkerFlags.objects.create(worker=worker)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20170120_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetracking_enabled', models.BooleanField(default=True, help_text='enable timetracking for this worker', verbose_name='timetracking enabled')),
                ('can_track_time', models.BooleanField(default=False, help_text='allow this worker to start/stop work timer', verbose_name='can track time')),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='company.Worker')),
            ],
        ),
        migrations.RunPython(create_worker_flags, migrations.RunPython.noop)
    ]
