# Generated by Django 2.0 on 2017-02-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_auto_20170209_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_jobsite_required',
            field=models.BooleanField(default=True, help_text='Require that all projects have a jobsite.', verbose_name='Jobsite Required'),
        ),
    ]
