# Generated by Django 2.0 on 2017-03-13 21:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import systori.lib.models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_company_is_jobsite_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Name')),
                ('is_template', models.BooleanField(default=False)),
                ('effective', models.DateField(default=datetime.date.today, help_text='Date on which worker officially started working.', null=True, verbose_name='Effective Date')),
                ('requires_time_tracking', models.BooleanField(default=True, help_text='Enable this to allow workers time to be tracked and for timesheets to be generated.', verbose_name='Time Tracking & Timesheets')),
                ('rate', models.DecimalField(decimal_places=2, help_text="Workers' compensation amount in local currency", max_digits=14, verbose_name='Rate')),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('flat', 'Flat Fee')], default='hourly', max_length=128, verbose_name='Rate Type')),
                ('vacation', models.IntegerField(default=1200, help_text='Vacation time (in hours) accumulated every month.', verbose_name='Vacation')),
                ('work_start', models.TimeField(default=datetime.time(7, 0), help_text='Local time at which worker is expected to start working.', verbose_name='Work Start')),
                ('morning_break_start', models.TimeField(blank=True, default=datetime.time(9, 0), help_text='Start of morning break in local time.', null=True, verbose_name='Morning Break Start')),
                ('morning_break_end', models.TimeField(blank=True, default=datetime.time(9, 30), help_text='End of morning break in local time.', null=True, verbose_name='Morning Break End')),
                ('lunch_break_start', models.TimeField(blank=True, default=datetime.time(12, 30), help_text='Start of lunch break in local time.', null=True, verbose_name='Lunch Break Start')),
                ('lunch_break_end', models.TimeField(blank=True, default=datetime.time(13, 0), help_text='End of lunch break in local time.', null=True, verbose_name='Lunch Break End')),
                ('work_end', models.TimeField(default=datetime.time(16, 0), help_text='Local time at which worker is expected to finish working.', verbose_name='Work End')),
                ('abandoned_timer_penalty', models.IntegerField(default=-60, help_text='Penalty (in hours) applies to work day of a worker who manually starts and then fails to stop their timer at the end of the day.', verbose_name='Abandoned Timer Penalty')),
            ],
            bases=(models.Model, systori.lib.models.RateType),
        ),
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Rate')),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('flat', 'Flat Fee')], default='hourly', max_length=128, verbose_name='Rate Type')),
            ],
            bases=(models.Model, systori.lib.models.RateType),
        ),
        migrations.AddField(
            model_name='worker',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.Contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.Worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='labor_types',
            field=models.ManyToManyField(blank=True, related_name='workers', to='company.LaborType'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='can_track_time',
            field=models.BooleanField(default=False, help_text='Worker will be able to start and stop their own work timer. Requires that "Time Tracking & Timesheets" is also enabled.', verbose_name='Allowed to track their own time?'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_accountant',
            field=models.BooleanField(default=False, help_text='Access to financial information.', verbose_name='Accountant'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Must be enabled to allow worker access to the company. Unchecking this will completely disable access for the worker and you will not be able to assign tasks to them in the daily planner.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_foreman',
            field=models.BooleanField(default=False, help_text='Manage workers in the field.', verbose_name='Foreman'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_laborer',
            field=models.BooleanField(default=True, help_text='Limited access in the field.', verbose_name='Laborer'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='Has full and unlimited access.', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Manage projects and perform administrative tasks.', verbose_name='Staff'),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Berlin'),
        ),
    ]
