# Generated by Django 2.0 on 2017-03-14 00:53

from decimal import Decimal
from django.db import migrations
from postgres_schema.operations import RunInSchemas


def add_contracts(apps, schema_editor):
    Worker = apps.get_model("company", "Worker")
    Contract = apps.get_model("company", "Contract")
    for worker in Worker.objects.all():
        worker.contract = Contract.objects.create(
            worker=worker,
            requires_time_tracking=worker.is_timetracking_enabled,
            rate=Decimal("0.00"),
        )
        worker.save()


class Migration(migrations.Migration):

    dependencies = [("company", "0009_auto_20170313_2228")]

    operations = [RunInSchemas(migrations.RunPython(add_contracts))]
