# Generated by Django 2.0 on 2017-03-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("company", "0010_auto_20170314_0153")]

    operations = [
        migrations.RemoveField(model_name="worker", name="is_timetracking_enabled")
    ]
