# Generated by Django 2.0.13 on 2019-07-30 20:10

from django.db import migrations, models
from postgres_schema.operations import RunInTemplate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("project", "0001_initial"),
        ("task", "0001_initial"),
    ]

    operations = [
        RunInTemplate(
            migrations.AddField(
                model_name="dailyplan",
                name="tasks",
                field=models.ManyToManyField(related_name="dailyplans", to="task.Task"),
            )
        ),
        RunInTemplate(
            migrations.AddField(
                model_name="dailyplan",
                name="workers",
                field=models.ManyToManyField(
                    related_name="dailyplans",
                    through="project.TeamMember",
                    to="company.Worker",
                ),
            )
        ),
    ]
