# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def move_equipment(apps, schema_editor):
    from systori.apps.company.models import Company

    DailyPlan = apps.get_model("project", "DailyPlan")
    EquipmentAssignment = apps.get_model("project", "EquipmentAssignment")
    for company in Company.objects.all():
        company.activate()
        for dailyplan in DailyPlan.objects.all():
            for equipment in dailyplan.equipment.all():
                EquipmentAssignment.objects.create(
                    dailyplan=dailyplan, equipment=equipment
                )


class Migration(migrations.Migration):

    dependencies = [("equipment", "0001_initial"), ("project", "0002_dailyplan_tasks")]

    operations = [
        migrations.CreateModel(
            name="EquipmentAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dailyplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_equipment",
                        to="project.DailyPlan",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="equipment.Equipment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dailyplan",
            name="equipment2",
            field=models.ManyToManyField(
                related_name="dailyplans2",
                through="project.EquipmentAssignment",
                to="equipment.Equipment",
            ),
        ),
        migrations.RunPython(move_equipment),
        migrations.RemoveField(model_name="dailyplan", name="equipment"),
        migrations.RenameField(
            model_name="dailyplan", old_name="equipment2", new_name="equipment"
        ),
    ]
