# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("project", "0003_auto_20160621_0450")]

    operations = [
        migrations.AlterField(
            model_name="dailyplan",
            name="equipment",
            field=models.ManyToManyField(
                related_name="dailyplans",
                through="project.EquipmentAssignment",
                to="equipment.Equipment",
            ),
        )
    ]
