# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20160707_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsite',
            name='travel_time',
            field=models.PositiveIntegerField(blank=True, help_text='in minutes', null=True, verbose_name='Travel time'),
        ),
    ]
