# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_jobsite_travel_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-is_foreman', 'worker__user__first_name']},
        ),
        migrations.RenameField(
            model_name='dailyplan',
            old_name='accesses',
            new_name='workers',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='access',
            new_name='worker',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='dailyplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.DailyPlan'),
        ),
    ]
