# Generated by Django 2.0 on 2017-09-15 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160720_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobsite',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='day',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Day'),
        ),
    ]
