# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20160720_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='level_1_zfill',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Level 1 Zero Fill'),
        ),
    ]
