# Generated by Django 2.0b1 on 2017-10-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("project", "0007_auto_20170915_1537")]

    operations = [migrations.RemoveField(model_name="project", name="account")]
