# Generated by Django 2.0.1 on 2018-01-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("project", "0008_remove_project_account")]

    operations = [migrations.RemoveField(model_name="jobsite", name="travel_time")]
