# Generated by Django 2.1.7 on 2019-02-27 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_jobsite_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyplan',
            name='end',
            field=models.TimeField(default=datetime.time(16, 0), verbose_name='End'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='start',
            field=models.TimeField(default=datetime.time(7, 0), verbose_name='Start'),
        ),
    ]
