# Generated by Django 2.1.8 on 2019-07-30 15:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import systori.lib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Manufacturer')),
                ('license_plate', models.CharField(blank=True, max_length=10, verbose_name='license plate')),
                ('number_of_seats', models.IntegerField(default=2, verbose_name='number of seats')),
                ('icon', models.ImageField(blank=True, upload_to='', verbose_name='Icon')),
                ('fuel', models.CharField(choices=[('gasoline', 'gasoline'), ('premium_gasoline', 'premium gasoline'), ('diesel', 'diesel'), ('premium_diesel', 'premium diesel'), ('electric', 'electric')], default='diesel', max_length=255, verbose_name='fuel')),
                ('last_refueling_stop', models.DateTimeField(blank=True, null=True, verbose_name='last refueling stop')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Rate')),
                ('rate_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('flat', 'Flat Fee')], default='hourly', max_length=128, verbose_name='Rate Type')),
            ],
            bases=(models.Model, systori.lib.fields.RateType),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='mileage')),
                ('description', models.TextField(verbose_name='description')),
                ('contractor', models.CharField(blank=True, max_length=100, verbose_name='contractor')),
                ('cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='cost')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment')),
            ],
        ),
        migrations.CreateModel(
            name='RefuelingStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='mileage')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='distance')),
                ('liters', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='refueled liters')),
                ('price_per_liter', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='price per liter')),
                ('average_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='average consumption')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='equipment.EquipmentType'),
        ),
    ]
