# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('mileage', models.IntegerField(verbose_name='mileage')),
                ('description', models.TextField(verbose_name='description')),
                ('repaired', models.BooleanField(verbose_name='repaired')),
                ('contractor', models.CharField(max_length=100, verbose_name='contractor')),
                ('cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'defect',
                'verbose_name_plural': 'defects',
            },
        ),
        migrations.CreateModel(
            name='RefuelingStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(db_index=True, default=datetime.datetime(2016, 8, 10, 23, 8, 53, 375839))),
                ('mileage', models.IntegerField(verbose_name='mileage')),
                ('liters', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='refueled liters')),
                ('price_per_liter', models.FloatField(verbose_name='price per liter')),
                ('average_consumption', models.FloatField(blank=True, editable=False, null=True, verbose_name='average consumption')),
            ],
            options={
                'verbose_name': 'refueling stop',
                'verbose_name_plural': 'refueling stops',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='fuel',
            field=models.CharField(choices=[('gasoline', 'gasoline'), ('diesel', 'diesel'), ('electric', 'electric')], default='diesel', max_length=255, verbose_name='fuel'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_refueling_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last refueling stop'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='license_plate',
            field=models.CharField(blank=True, max_length=10, verbose_name='license plate'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='number_of_seats',
            field=models.IntegerField(default=2, verbose_name='number of seats'),
        ),
        migrations.AddField(
            model_name='refuelingstop',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment'),
        ),
        migrations.AddField(
            model_name='defect',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment', verbose_name='equipment'),
        ),
    ]
