# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_auto_20160818_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='refuelingstop',
            options={},
        ),
    ]
