FROM python:3.6.5-stretch AS base

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/*
RUN locale-gen de_DE.UTF-8 && locale-gen en_US.UTF-8
RUN pip install --upgrade pip pipenv

ARG SSH_PRIVATE_KEY
RUN mkdir /root/.ssh/
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts


ADD . /app
WORKDIR /app
RUN export WORKON_HOME=/venv && mkdir $WORKON_HOME && pipenv install --dev

CMD ["/startup_systori.sh"]