# Generated by Django 2.0.13 on 2019-07-30 20:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from postgres_schema.operations import RunInTemplate


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        RunInTemplate(
            migrations.CreateModel(
                name="Account",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "account_type",
                        models.CharField(
                            choices=[
                                ("asset", "Asset"),
                                ("liability", "Liability"),
                                ("income", "Income"),
                                ("expense", "Expense"),
                            ],
                            max_length=32,
                            verbose_name="Account Type",
                        ),
                    ),
                    (
                        "asset_type",
                        models.CharField(
                            choices=[
                                ("bank", "Bank"),
                                ("receivable", "Accounts Receivable"),
                            ],
                            max_length=32,
                            null=True,
                            verbose_name="Asset Type",
                        ),
                    ),
                    ("code", models.CharField(max_length=32, verbose_name="Code")),
                    (
                        "name",
                        models.CharField(
                            blank=True, max_length=512, verbose_name="Name"
                        ),
                    ),
                ],
                options={"ordering": ["code"], "abstract": False},
            )
        ),
        RunInTemplate(
            migrations.CreateModel(
                name="Entry",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    (
                        "value",
                        models.DecimalField(
                            decimal_places=2, max_digits=14, verbose_name="Value"
                        ),
                    ),
                    (
                        "entry_type",
                        models.CharField(
                            choices=[
                                ("payment", "Payment"),
                                ("refund-credit", "Refund Credit"),
                                ("discount", "Discount"),
                                ("work-debit", "Work Debit"),
                                ("flat-debit", "Flat Debit"),
                                ("refund", "Refund"),
                                ("adjustment", "Adjustment"),
                                ("other", "Other"),
                            ],
                            default="other",
                            max_length=32,
                            verbose_name="Entry Type",
                        ),
                    ),
                    (
                        "value_type",
                        models.CharField(
                            choices=[
                                ("net", "Net"),
                                ("tax", "Tax"),
                                ("gross", "Gross"),
                            ],
                            max_length=32,
                            verbose_name="Value Type",
                        ),
                    ),
                    (
                        "reconciled_on",
                        models.DateField(null=True, verbose_name="Date Reconciled"),
                    ),
                    (
                        "is_reconciled",
                        models.BooleanField(default=False, verbose_name="Reconciled"),
                    ),
                    (
                        "account",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="entries",
                            to="accounting.Account",
                        ),
                    ),
                ],
                options={
                    "ordering": ["transaction__transacted_on", "id"],
                    "abstract": False,
                },
            )
        ),
        RunInTemplate(
            migrations.CreateModel(
                name="Transaction",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("notes", models.TextField(blank=True)),
                    (
                        "transacted_on",
                        models.DateField(
                            default=datetime.date.today, verbose_name="Date Transacted"
                        ),
                    ),
                    (
                        "finalized_on",
                        models.DateField(null=True, verbose_name="Date Finalized"),
                    ),
                    (
                        "is_finalized",
                        models.BooleanField(default=False, verbose_name="Finalized"),
                    ),
                    ("is_revenue_recognized", models.BooleanField(default=False)),
                    (
                        "recorded_on",
                        models.DateTimeField(
                            auto_now_add=True, verbose_name="Date Recorded"
                        ),
                    ),
                    (
                        "transaction_type",
                        models.CharField(
                            choices=[
                                ("invoice", "Invoice"),
                                ("payment", "Payment"),
                                ("adjustment", "Adjustment"),
                                ("refund", "Refund"),
                            ],
                            max_length=32,
                            null=True,
                            verbose_name="Transaction Type",
                        ),
                    ),
                ],
                options={"abstract": False},
            )
        ),
    ]
