# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 14:41
from __future__ import unicode_literals

from django.db import migrations


def delete_orphan_payments(apps, schema_editor):
    from systori.apps.company.models import Company
    from systori.apps.accounting.models import Transaction
    from systori.apps.document.models import Payment

    for company in Company.objects.all():
        company.activate()

        txns = Transaction.objects.\
                filter(transaction_type=Transaction.PAYMENT).\
                prefetch_related('payment')

        for txn in txns.all():
            try:
                txn.payment
            except Payment.DoesNotExist:
                print(company.schema, txn.recorded_on)
                print('\t', 'entry count:', txn.entries.count())
                for entry in txn.entries.all():
                    if entry.account.is_receivable:
                        print('\t', entry.account.job.project.name, entry.account.job.name)
                txn.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_added_value_fields'),
    ]

    operations = [
        migrations.RunPython(delete_orphan_payments)
    ]
