# Generated by Django 2.2.4 on 2019-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='en', max_length=2, verbose_name='language'),
        ),
    ]
