# Generated by Django 2.2.4 on 2019-08-30 17:05

from django.db import migrations, models
from django.conf import settings


def update_default_language(apps, schema_editor):
    """
    Make sure existing users who haven't manually set their language, get a default value
    """
    User = apps.get_model("user", "User")
    for user in User.objects.all():
        if not user.language:
            user.language = settings.LANGUAGE_CODE
            user.save()


class Migration(migrations.Migration):

    dependencies = [("user", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("de", "Deutsch"), ("en", "English")],
                default="en",
                max_length=2,
                verbose_name="language",
            ),
        ),
        migrations.RunPython(update_default_language),
    ]
