# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_job_to_task(apps, schema_editor):
    from systori.apps.company.models import Company
    Task = apps.get_model("task", "Task")
    for company in Company.objects.all():
        company.activate()
        for task in Task.objects.all():
            task.job = task.taskgroup.job
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160815_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('order',), 'verbose_name': 'Line Item', 'verbose_name_plural': 'Line Items'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order',), 'verbose_name': 'Task', 'verbose_name_plural': 'Task'},
        ),
        migrations.AlterModelOptions(
            name='taskgroup',
            options={'ordering': ('order',), 'verbose_name': 'Task Group', 'verbose_name_plural': 'Task Groups'},
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Job'),
        ),
        migrations.RunPython(add_job_to_task),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Job'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_taskgroups', to='task.Job'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='level',
            field=models.PositiveIntegerField(editable=False, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Price'),
        ),
    ]
