# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160815_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskgroup',
            options={'ordering': ('order',), 'verbose_name': 'Task Group', 'verbose_name_plural': 'Task Groups'},
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_taskgroups', to='task.Job'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='level',
            field=models.PositiveIntegerField(default=2, editable=False, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='taskinstance',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Order'),
        ),
    ]
