# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def make_job_inherit_from_group(apps, schema_editor):
    from systori.apps.company.models import Company
    Job = apps.get_model("task", "Job")
    Group = apps.get_model("task", "Group")
    for company in Company.objects.all():
        company.activate()
        for job in Job.objects.all():
            job.root = Group.objects.create(
                id=job.id,
                name=job.name,
                description=job.description,
                order=job.job_code
            )
            job.save()
        schema_editor.execute(
            "select setval(pg_get_serial_sequence('task_group', 'id'), max(id)) from task_group;"
        )


def copy_groups_and_relink_tasks(apps, schema_editor):
    from systori.apps.company.models import Company
    Job = apps.get_model("task", "Job")
    Group = apps.get_model("task", "Group")
    for company in Company.objects.all():
        company.activate()
        for job in Job.objects.all():
            for taskgroup in job.taskgroups.all():
                group = Group.objects.create(
                    parent=job.root,
                    name=taskgroup.name,
                    description=taskgroup.description,
                    order=taskgroup.order + 1 + job.taskgroup_offset
                )
                for task in taskgroup.tasks.all():
                    task.job = job
                    task.group = group
                    task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160815_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=512, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='task.Group')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),

        # Migrate data so that Job inherits from Group

        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Job'},
        ),
        migrations.AddField(
            model_name='job',
            name='root',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='task.Group')
        ),
        migrations.RunPython(make_job_inherit_from_group),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AlterField(
            model_name='job',
            name='root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, to='task.Group'),
        ),

        # Migrate TaskGroup to Group

        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Group'),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alltasks', to='task.Job'),
        ),
        migrations.RunPython(copy_groups_and_relink_tasks),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alltasks', to='task.Job'),
        ),

        # Cleanup...

        migrations.RemoveField(
            model_name='task',
            name='taskgroup',
        ),
        migrations.DeleteModel('taskgroup'),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_code',
        ),
        migrations.RemoveField(
            model_name='job',
            name='taskgroup_offset',
        ),
    ]
