# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160815_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(verbose_name='api token', null=True)),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=512, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('parent', models.ForeignKey('self', models.CASCADE, null=True, related_name='groups')),
                ('depth', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.RenameModel('Job', 'OldJob'),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('billing_method', models.CharField(max_length=128, default='fixed_price', choices=[('fixed_price', 'Fixed Price'), ('time_and_materials', 'Time and Materials')], verbose_name='Billing Method')),
                ('is_revenue_recognized', models.BooleanField(default=False)),
                ('status', django_fsm.FSMField(max_length=50, default='draft', choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('approved', 'Approved'), ('started', 'Started'), ('completed', 'Completed')])),
                ('account', models.OneToOneField('accounting.Account', models.SET_NULL, related_name='job', null=True)),
                ('project', models.ForeignKey('project.Project', models.CASCADE, related_name='jobs')),
                ('root', models.OneToOneField('task.Group', models.CASCADE, parent_link=True, primary_key=True, related_name='+')),
            ],
            bases=('task.Group',),
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Job',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='job',
            field=models.ForeignKey('task.Job', models.CASCADE, null=True, related_name='all_groups'),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey('task.Job', models.CASCADE, null=True, related_name='all_tasks'),
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey('task.Group', models.CASCADE, null=True, related_name='tasks'),
        ),
    ]
