# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_job_to_task(apps, schema_editor):
    from systori.apps.company.models import Company
    Task = apps.get_model("task", "Task")
    for company in Company.objects.all():
        company.activate()
        for task in Task.objects.all():
            task.job = task.taskgroup.job
            task.save()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160906_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Job'),
        ),
        migrations.RunPython(add_job_to_task),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Job'),
        ),
    ]
