# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 03:53
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from systori.lib.templatetags.customformatting import money, ubrdecimal


def upgrade_taskinstance_to_task(apps, schema_editor):
    from systori.apps.company.models import Company
    Job = apps.get_model("task", "Job")
    for company in Company.objects.all():
        company.activate()

        for job in Job.objects.all():

            variant_group = 100

            for task in job.alltasks.all():

                order_max = None

                is_variant_mode = task.taskinstances.count() > 1
                if is_variant_mode:
                    if variant_group == 100:
                        print('Project {}: {}, Job {}: {}'.format(
                            task.job.project.id, task.job.project.name,
                            task.job.pk, task.job.root.name)
                        )
                    print('  Variations for {}: {}'.format(task.id, task.name))
                    variant_group += 1
                    task.variant_group = variant_group
                    task.save()

                for taskinstance in task.taskinstances.order_by('-selected'):

                    if not taskinstance.selected and not is_variant_mode:
                        raise AssertionError("If only one task instance it must be selected.")

                    if not taskinstance.selected:
                        if order_max is None:
                            order_max = task.group.tasks.aggregate(models.Max('order')).get('order__max')
                        order_max += 1
                        task.id = None
                        task.order = order_max
                        task.variant_serial += 1
                        task.save()
                        print("    Variant: {}.{}".format(task.variant_group, task.variant_serial))
                    elif is_variant_mode:
                        print("    Primary: {}.{}".format(task.variant_group, task.variant_serial))

                    task.price = Decimal('0.00')
                    if is_variant_mode: print("    Line items ", end='')
                    for lineitem in taskinstance.lineitems.all():
                        lineitem.total = lineitem.qty * lineitem.price
                        task.price += lineitem.total
                        lineitem.task = task
                        lineitem.save()
                        if is_variant_mode: print(".", end='')
                    if is_variant_mode: print("")
                    task.total = task.qty * task.price
                    task.save()


def remove_old_content_types(apps, schema_editor):
    from systori.apps.company.models import Company as Company
    from django.contrib.contenttypes.models import ContentType
    for company in Company.objects.all():
        company.activate()
        ContentType.objects.filter(app_label='task', model='taskgroup').delete()
        ContentType.objects.filter(app_label='task', model='taskinstance').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_group_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='task',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Total'),
        ),
        migrations.RenameField(
            model_name='task',
            old_name='is_optional',
            new_name='is_provisional',
        ),
        migrations.AddField(
            model_name='task',
            name='variant_group',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='variant_serial',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),

        migrations.RenameField(
            model_name='lineitem',
            old_name='unit_qty',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Total'),
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='task_qty',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('order',), 'verbose_name': 'Line Item', 'verbose_name_plural': 'Line Items'},
        ),

        # Add task to lineitem, allowing NULLs
        migrations.AddField(
            model_name='lineitem',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='task.Task'),
        ),
        # properly set all of the jobs
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE', reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(upgrade_taskinstance_to_task),
        # Now alter making it NOT NULL
        migrations.AlterField(
            model_name='lineitem',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='task.Task'),
        ),
        # Cleanup...
        migrations.RemoveField('lineitem', 'taskinstance'),
        migrations.DeleteModel('taskinstance'),
        migrations.RunPython(remove_old_content_types),
    ]
