# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20160817_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('order',), 'verbose_name': 'Line Item', 'verbose_name_plural': 'Line Items'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('order',), 'verbose_name': 'Task', 'verbose_name_plural': 'Task'},
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.Job'),
        ),
        migrations.AddField(
            model_name='taskinstance',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='level',
            field=models.PositiveIntegerField(editable=False, verbose_name='Level'),
        ),
    ]
