# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='billable',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='is_labor',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='is_material',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='complete',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Completed'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='price_equation',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='qty_equation',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='total_equation',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='qty_equation',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='total_equation',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='unit',
            field=models.CharField(max_length=512, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=14, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unit',
            field=models.CharField(max_length=512, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='task',
            name='price_equation',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
