# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161212174138 on 2016-12-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models
from postgres_schema.operations import RunInSchema
import django.db.models.deletion
import tsvector_field


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='search',
            field=tsvector_field.SearchVectorField(columns=[tsvector_field.WeightedColumn('name', 'A'), tsvector_field.WeightedColumn('description', 'D')], language='german'),
        ),
        RunInSchema(tsvector_field.IndexSearchVector('group', 'search')),
        migrations.AddField(
            model_name='task',
            name='search',
            field=tsvector_field.SearchVectorField(columns=[tsvector_field.WeightedColumn('name', 'A'), tsvector_field.WeightedColumn('description', 'D')], language='german'),
        ),
        RunInSchema(tsvector_field.IndexSearchVector('task', 'search')),
        migrations.AlterField(
            model_name='job',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='project.Project'),
        ),
    ]
