# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161211030609 on 2016-12-11 03:20
from __future__ import unicode_literals

import tsvector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='search',
            field=tsvector.SearchVectorField(columns=[tsvector.WeightedColumn('name', 'A'), tsvector.WeightedColumn('description', 'D')], language='german'),
        ),
        migrations.AddField(
            model_name='task',
            name='search',
            field=tsvector.SearchVectorField(columns=[tsvector.WeightedColumn('name', 'A'), tsvector.WeightedColumn('description', 'D')], language='german'),
        ),
    ]
