# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161130220531 on 2016-12-10 06:07
from __future__ import unicode_literals

from django.db import migrations
import systori.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='search',
            field=systori.db.fields.TSVectorField(columns=[systori.db.fields.TSVector('name', 'A'), systori.db.fields.TSVector('description', 'D')], language='german'),
        ),
        migrations.AddField(
            model_name='task',
            name='search',
            field=systori.db.fields.TSVectorField(columns=[systori.db.fields.TSVector('name', 'A'), systori.db.fields.TSVector('description', 'D')], language='german'),
        ),
    ]
