# Generated by Django 2.0 on 2017-04-25 15:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("task", "0010_auto_20170425_0355")]

    operations = [
        migrations.AlterField(
            model_name="expendreport",
            name="expended",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=13,
                verbose_name="Expended",
            ),
        ),
        migrations.AlterField(
            model_name="lineitem",
            name="qty",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=13,
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="progressreport",
            name="complete",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=13,
                verbose_name="Complete",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="qty",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=Decimal("0.00"),
                max_digits=13,
                null=True,
                verbose_name="Quantity",
            ),
        ),
    ]
