# Generated by Django 2.0.13 on 2019-07-30 20:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
from postgres_schema.operations import RunInTemplate


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        RunInTemplate(
            migrations.CreateModel(
                name="Material",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("name", models.CharField(max_length=512, verbose_name="Name")),
                ],
            )
        ),
        RunInTemplate(
            migrations.CreateModel(
                name="MaterialType",
                fields=[
                    (
                        "id",
                        models.AutoField(
                            auto_created=True,
                            primary_key=True,
                            serialize=False,
                            verbose_name="ID",
                        ),
                    ),
                    ("name", models.CharField(max_length=512, verbose_name="Name")),
                    (
                        "price",
                        models.DecimalField(
                            decimal_places=4,
                            default=Decimal("0.00"),
                            max_digits=14,
                            verbose_name="Price",
                        ),
                    ),
                ],
            )
        ),
        RunInTemplate(
            migrations.AddField(
                model_name="material",
                name="material_type",
                field=models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="materials",
                    to="inventory.MaterialType",
                ),
            )
        ),
    ]
