# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0003_timer_altered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2016, 6, 30, 6, 37, 39, 74147, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timer',
            name='kind',
            field=models.PositiveIntegerField(choices=[(10, 'Work'), (20, 'Holiday'), (30, 'Illness'), (5, 'Correction'), (15, 'Education')], db_index=True, default=10),
        ),
        migrations.AlterField(
            model_name='timer',
            name='start',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
