# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


def convert_kind(apps, schema_editor):
    from systori.apps.company.models import Company
    Timer = apps.get_model("timetracking", "Timer")
    for company in Company.objects.all():
        company.activate()
        for timer in Timer.objects.all():
            timer.kind = {
                '5': 'correction',
                '10': 'work',
                '15': 'training',
                '20': 'holiday',
                '30': 'illness'
            }[timer.kind]
            timer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0008_auto_20160802_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='kind',
            field=models.CharField(choices=[('work', 'Work'), ('holiday', 'Holiday'), ('illness', 'Illness'), ('correction', 'Correction'), ('training', 'Training')], db_index=True, default='work', max_length=32),
        ),
        migrations.RunPython(convert_kind),
    ]
