# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-23 17:29
from __future__ import unicode_literals

from django.db import migrations, models


def convert_kind(apps, schema_editor):
    from systori.apps.company.models import Company
    Timer = apps.get_model("timetracking", "Timer")
    for company in Company.objects.all():
        company.activate()
        for timer in Timer.objects.all():
            timer.kind = {
                '5': 'correction',
                '10': 'work',
                '15': 'training',
                '20': 'holiday',
                '30': 'illness'
            }[timer.kind]
            timer.save()


def split_timers(apps, schema_editor):
    from systori.apps.company.models import Company
    from systori.apps.timetracking.models import Timer
    for company in Company.objects.all():
        company.activate()
        for timer in Timer.objects.all():

            if timer.start.hour < 7:
                timer.start = timer.start.replace(
                    hour=7, minute=0, second=0
                )
                timer.duration = None
                timer.save()

            if timer.duration >= 60 * 60 * 9:
                assert timer.start.hour < 9
                old_end = timer.end

                timer.end = timer.end.replace(
                    hour=9, minute=0, second=0
                )
                timer.duration = None
                timer.save()

                # Break 1: 9:00 - 9:30

                timer.id = None
                timer.start = timer.start.replace(
                    hour=9, minute=30, second=0
                )
                timer.end = timer.end.replace(
                    hour=12, minute=30, second=0
                )
                timer.duration = None
                timer.save()

                # Break 2: 12:30 - 13:00

                timer.id = None
                timer.start = timer.start.replace(
                    hour=13, minute=0, second=0
                )
                timer.end = old_end
                timer.duration = None
                timer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0008_auto_20160802_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='kind',
            field=models.CharField(choices=[('work', 'Work'), ('holiday', 'Holiday'), ('illness', 'Illness'), ('correction', 'Correction'), ('training', 'Training')], db_index=True, default='work', max_length=32),
        ),
        migrations.RunPython(convert_kind),
        migrations.RunPython(split_timers),
    ]
