# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0009_auto_20160823_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='is_auto_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timer',
            name='is_auto_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
