# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def convert_user_to_worker(apps, schema_editor):
    from systori.apps.company.models import Company as Company
    Timer = apps.get_model("timetracking", "Timer")
    Worker = apps.get_model("company", "Worker")
    for company in Company.objects.all():
        company.activate()
        WorkerQuery = Worker.objects.filter(company_id=company.schema)
        for timer in Timer.objects.all():
            timer.worker = WorkerQuery.get(user_id=timer.user_id)
            timer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_worker'),
        ('timetracking', '0009_auto_20160823_1929'),
    ]

    operations = [

        # Create the 'access' based fields.

        migrations.AddField(
            model_name='timer',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='company.Worker'),
        ),

        # Lookup and set the 'access' fields.

        migrations.RunPython(convert_user_to_worker),

        # Make 'user_access' not null now that it's been set.

        migrations.AlterField(
            model_name='timer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='company.Worker'),
        ),

        # Remove the 'user' based fields.

        migrations.RemoveField('timer', 'user'),
        migrations.RemoveField('timer', 'altered_by'),

    ]
