# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0010_convert_user_to_access'),
    ]

    operations = [

        # Make 'user_access' not null now that it's been set.

        migrations.AlterField(
            model_name='timer',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='company.Worker'),
        ),

        # Remove the 'user' based fields.

        migrations.RemoveField('timer', 'user'),
        migrations.RemoveField('timer', 'altered_by'),

    ]
