# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20160403_0209'),
        ('timetracking', '0010_convert_user_to_access'),
    ]

    operations = [
        migrations.RenameField('timer', 'user_access', 'user'),
        migrations.RenameField('timer', 'altered_by_access', 'altered_by'),
    ]
