# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-31 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0011_convert_user_to_access_cleanup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='kind',
            field=models.CharField(choices=[('work', 'Work'), ('holiday', 'Holiday'), ('illness', 'Illness'), ('correction', 'Correction'), ('training', 'Training'), ('public_holiday', 'Public holiday'), ('paid_leave', 'Paid leave')], db_index=True, default='work', max_length=32),
        ),
    ]
