# Generated by Django 2.0 on 2017-03-05 13:58

from django.db import migrations, models
from postgres_schema.operations import RunInSchemas


def rename_timer_kinds(apps, schema_editor):
    Timer = apps.get_model("timetracking", "Timer")
    for timer in Timer.objects.filter(kind__in=['holiday', 'training', 'illness']):
        if timer.kind == 'holiday':
            timer.kind = 'vacation'
        elif timer.kind == 'training':
            timer.kind = 'work'
        elif timer.kind == 'illness':
            timer.kind = 'sick'
        else:
            raise AttributeError()
        timer.save()

    from systori.apps.document.models import Timesheet
    for ts in Timesheet.objects.all():
        ts.json['vacation_correction'] = ts.json['holiday_correction']
        ts.json['vacation_correction_notes'] = ts.json['holiday_correction_notes']
        ts.calculate()
        ts.save()


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0012_auto_20170201_1525'),
        ('document', '0010_auto_20170214_0028')
    ]

    operations = [
        RunInSchemas(migrations.RunPython(rename_timer_kinds)),
        migrations.AlterField(
            model_name='timer',
            name='kind',
            field=models.CharField(choices=[('work', 'Work'), ('vacation', 'Vacation'), ('sick', 'Sick'), ('public_holiday', 'Public holiday'), ('paid_leave', 'Paid leave'), ('unpaid_leave', 'Unpaid leave')], db_index=True, default='work', max_length=32),
        ),
    ]
