# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-02-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0012_auto_20170131_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='job_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.JobSite'),
        ),
    ]
